### ISSUE TITLE
Can't disable artwork column

### ISSUE THREAD

**Issue by bg3dev** [dscottbuch/cTiVo#276]
-Right-click/Control-click on Art column in browser window
- Deselect option for Art
- Quit app
- Re-open app

Art is back. 

Version 3.0 alpha5 (773)

**Comment by mackworth** [comment]
Well, that's weird.  (Anybody else see the same thing?)
 Any other columns do that? 
Which OS are you on? 
Which Preferred Artwork is selected in Preferences?
Is the Art column working ok when it's there? Does it stay away as long as you don't close the app?
Can you email me your preference file (`Cmd-Shift-G` ` ~/Library/Preferences` then select `com.cTiVo.ctivo.plist` file)?  then mail to mackworth at aol dot com.

**Comment by bg3dev** [comment]
Any other columns do that?
- looks like it's returning to default views on launch. I didn't realize that, but I tried adding some other columns today and they vanished after re-opening.
Which OS are you on?
- High Sierra (happens on both current and public beta build)
Does it stay away as long as you don't close the app?
- yep.
Which Preferred Artwork is selected in Preferences?
- Tivo. Though it doesn't matter what it's set to. See first answer. Tried None as well. 

Will try to get the pref file to you after I try the beta.

**Comment by mackworth** [comment]
Are other preferences sticking across runs?  e.g. Download Directory, or Format choice.  What about the Download columns or Subscription Columns?
Does this happen with 2.5.1?  (No Art column, but check the others).

**Comment by bg3dev** [comment]
Tried starting over with a new pref file and cTivo 3.0 beta 1 today, but cTivo gave spinning wheel of death on launch. I’ll file a separate issue for that. Maybe it’s related, dunno. Answers to your questions below. 

Are other preferences sticking across runs? e.g. Download Directory, or Format choice. 
- other prefs work fine
What about the Download columns or Subscription Columns?
- same issue, even with new pref file and 2.5.1
Does this happen with 2.5.1? (No Art column, but check the others).
- looks like it happens with 2.5.1 if I add other columns as well, then relaunch. So, not a new issue

I’m guessing this isn’t happening to you when you try it. So who knows what the issue is. I’ve been through multiple versions of cTivo, OS, and upgraded this hard drive a number of times so it may be something I introduced along the way related to permissions or something.

**Comment by mackworth** [comment]
beta1 definitely has some issues; update coming shortly.
You might look in ~/Library/Preferences and see if there's any extraneous files com.ctivo.ctio.  The system creates a temporary version to update preferences, and there are rports that it can get stuck. 
If you want to "start over" then best to go to Terminal (while ctivo is not running, and then wait 10 seconds), and type 'defaults delete com.ctivo.ctivo".
If you really want to be sure that worked, then you have to log out and log back in.

**Comment by mackworth** [comment]
And I did do some work in Beta2 on the art column as well. Let me know.

**Comment by mackworth** [comment]
So pretty sure this is fixed now.  Let me know if you find otherwise in Beta2 or later.

**Comment by bg3dev** [comment]
I still have the same issue where the art column comes back on relaunch. Happening on two different computers, with two different operating systems (Sierra, High Sierra) using cTivo beta 3. I’m guessing when you try this in a new user account on your own computer you’re not seeing this?

**Comment by mackworth** [comment]
So, yes. I am now able to recreate it. Nothing to do with the Art column, true for any column, and I can also recreate it with the existing 2.5.1, so it's not a new problem.  I'm curious why it hasn't been reported before. 

The problem I have is this is a built-in function of Apple's TableView, and I see no way to modify its behavior.  So further experiments needed.

**Comment by mackworth** [comment]
Okay, so I've isolated down the problem; still need to figure out how to fix, but a workaround should be:

In Terminal type `defaults write com.cTiVo.cTiVo HasMultipleTivos -bool YES`

Please confirm if that fixes it for you.

**Comment by bg3dev** [comment]
Yep! The terminal command worked.

**Comment by mackworth** [comment]
Okay, this should be fixed in the [release candidate 1](https://github.com/dscottbuch/cTiVo/releases)  To really test, you'll need to delete your preferences file `~/Library/Preferences/com.ctivo.ctivo.plist`.  Let me know if you have any further problem.

Thank you for being persistent here!

**Comment by bg3dev** [comment]
RC1 worked with a fresh pref. Thanks again!
