### ISSUE TITLE
cTiVo seems to be stuck 

### ISSUE THREAD

**Issue by kcossabo** [dscottbuch/cTiVo#98]
This has happened for the second time. Subscriptions are know, moved to Download Queue but never start to download. Asking to dequeue does not resolve the issue. 

The Logs seem to repeat this;
-----------------------------------------------------------------------------------------------
2015-03-28 08:33:17:061 MTTiVo>connection:didReceiveData:@711>TiVo Romio-living room (192.168.11.162:80/443) sent data
2015-03-28 08:33:17:061 MTTiVo>connectionDidFinishLoading:@781>Romio-living room (192.168.11.162:80/443) URL Connection completed 
2015-03-28 08:33:17:061 MTTiVo>connectionDidFinishLoading:@782>Data received is <?xml version="1.0" encoding="utf-8"?><TiVoContainer xmlns="http://www.tivo.com/developer/calypso-protocol-1.6/"><Details><ContentType>x-tivo-container/tivo-videos</ContentType><SourceFormat>x-tivo-container/tivo-dvr</SourceFormat><Title>Now Playing</Title><LastChangeDate>0x55169F38</LastChangeDate><TotalItems>553</TotalItems><UniqueId>/NowPlaying</UniqueId></Details><SortOrder>Type,CaptureDate</SortOrder><GlobalSort>Yes</GlobalSort><ItemStart>550</ItemStart><ItemCount>0</ItemCount></TiVoContainer>
2015-03-28 08:33:17:062 MTTiVo>startElement:@394>Romio-living room (192.168.11.162:80/443) Start: TiVoContainer
2015-03-28 08:33:17:062 MTTiVo>startElement:@394>Romio-living room (192.168.11.162:80/443) Start: Details
2015-03-28 08:33:17:062 MTTiVo>startElement:@394>Romio-living room (192.168.11.162:80/443) Start: ContentType
2015-03-28 08:33:17:062 MTTiVo>parserElement:@423>Romio-living room:  ContentType --> x-tivo-container/tivo-videos
2015-03-28 08:33:17:062 MTTiVo>endElement:@562>Unrecognized element: ContentType-->x-tivo-container/tivo-videos
2015-03-28 08:33:17:062 MTTiVo>startElement:@394>Romio-living room (192.168.11.162:80/443) Start: SourceFormat
2015-03-28 08:33:17:062 MTTiVo>parserElement:@423>Romio-living room:  SourceFormat --> x-tivo-container/tivo-dvr
2015-03-28 08:33:17:062 MTTiVo>endElement:@562>Unrecognized element: SourceFormat-->x-tivo-container/tivo-dvr
2015-03-28 08:33:17:062 MTTiVo>startElement:@394>Romio-living room (192.168.11.162:80/443) Start: Title
2015-03-28 08:33:17:062 MTTiVo>parserElement:@423>Romio-living room:  Title --> Now Playing
2015-03-28 08:33:17:062 MTTiVo>endElement:@562>Unrecognized element: Title-->Now Playing
2015-03-28 08:33:17:062 MTTiVo>startElement:@394>Romio-living room (192.168.11.162:80/443) Start: LastChangeDate
2015-03-28 08:33:17:062 MTTiVo>parserElement:@423>Romio-living room:  LastChangeDate --> 0x55169F38
2015-03-28 08:33:17:062 MTTiVo>startElement:@394>Romio-living room (192.168.11.162:80/443) Start: TotalItems
2015-03-28 08:33:17:062 MTTiVo>parserElement:@423>Romio-living room:  TotalItems --> 553
2015-03-28 08:33:17:062 MTTiVo>endElement:@546>TotalItems: 553
2015-03-28 08:33:17:062 MTTiVo>startElement:@394>Romio-living room (192.168.11.162:80/443) Start: UniqueId
2015-03-28 08:33:17:062 MTTiVo>parserElement:@423>Romio-living room:  UniqueId --> /NowPlaying
2015-03-28 08:33:17:062 MTTiVo>endElement:@562>Unrecognized element: UniqueId-->/NowPlaying
2015-03-28 08:33:17:062 MTTiVo>parserElement:@423>Romio-living room:  Details --> /NowPlaying
2015-03-28 08:33:17:062 MTTiVo>endElement:@562>Unrecognized element: Details-->/NowPlaying
2015-03-28 08:33:17:062 MTTiVo>startElement:@394>Romio-living room (192.168.11.162:80/443) Start: SortOrder
2015-03-28 08:33:17:062 MTTiVo>parserElement:@423>Romio-living room:  SortOrder --> Type,CaptureDate
2015-03-28 08:33:17:062 MTTiVo>endElement:@562>Unrecognized element: SortOrder-->Type,CaptureDate
2015-03-28 08:33:17:062 MTTiVo>startElement:@394>Romio-living room (192.168.11.162:80/443) Start: GlobalSort
2015-03-28 08:33:17:062 MTTiVo>parserElement:@423>Romio-living room:  GlobalSort --> Yes
2015-03-28 08:33:17:062 MTTiVo>endElement:@562>Unrecognized element: GlobalSort-->Yes
2015-03-28 08:33:17:062 MTTiVo>startElement:@394>Romio-living room (192.168.11.162:80/443) Start: ItemStart
2015-03-28 08:33:17:062 MTTiVo>parserElement:@423>Romio-living room:  ItemStart --> 550
2015-03-28 08:33:17:062 MTTiVo>endElement:@549>ItemStart: 550
2015-03-28 08:33:17:062 MTTiVo>startElement:@394>Romio-living room (192.168.11.162:80/443) Start: ItemCount
2015-03-28 08:33:17:062 MTTiVo>parserElement:@423>Romio-living room:  ItemCount --> 0
2015-03-28 08:33:17:062 MTTiVo>endElement:@552>ItemCount: 0
2015-03-28 08:33:17:062 MTTiVo>parserElement:@423>Romio-living room:  TiVoContainer --> 0
2015-03-28 08:33:17:062 MTTiVo>endElement:@562>Unrecognized element: TiVoContainer-->0
2015-03-28 08:33:17:062 MTTiVo>parserDidEndDocument:@591>TiVo Romio-living room (192.168.11.162:80/443) finished batch
2015-03-28 08:33:17:062 MTTiVo>updateShowsStartingAt:withCount:@357>Getting Romio-living room (192.168.11.162:80/443) shows from 550 to 600
2015-03-28 08:33:17:062 MTTiVo>updateShowsStartingAt:withCount:@360>On TiVo Romio-living room (192.168.11.162:80/443); port 443
2015-03-28 08:33:17:062 MTTiVo>updateShowsStartingAt:withCount:@365>Tivo Romio-living room (192.168.11.162:80/443) URL String https://192.168.11.162:443/TiVoConnect?Command=QueryContainer&Container=%252FNowPlaying&Recurse=Yes&AnchorOffset=550&ItemCount=50
2015-03-28 08:33:17:062 MTProgramTableView>reloadData@69>Reload Program Table
2015-03-28 08:33:17:074 MTProgramTableView>sortedShows@205>Re-sorting Program table
2015-03-28 08:33:17:074 MTTiVoManager>tiVoShows@1454>reloading shows
2015-03-28 08:33:17:077 MTTiVo>manageDownloads:@646>HD ignoring notification MTNotificationDownloadQueueUpdated for Romio-living room (192.168.11.162:80/443)
2015-03-28 08:33:17:077 MTTiVo>manageDownloads:@643>Romio-living room (192.168.11.162:80/443) got manageDownload notification MTNotificationDownloadQueueUpdated
2015-03-28 08:33:17:077 MTTiVo>manageDownloads@658>Checking Romio-living room (192.168.11.162:80/443) queue
2015-03-28 08:33:17:078 MTTiVo>manageDownloads@672>Romio-living room (192.168.11.162:80/443) Checking for new download
2015-03-28 08:33:17:079 MTDownloadTableView>reloadData@125>Reloading DL table
2015-03-28 08:33:17:105 MTTiVo>manageDownloads:@646>Premiere ignoring notification MTNotificationDownloadQueueUpdated for Romio-living room (192.168.11.162:80/443)
-----------------------------------------------------------------------------------------------------

I turned logging up to verbose and see many of these;

-----------------------------------------------------------------------------------------------------
2015-03-28 08:33:16:953 MTProgramTableView>awakeFromNib@54>ProgramTable awakeFromNib
2015-03-28 08:33:16:953 MTProgramTableView>awakeFromNib@54>ProgramTable awakeFromNib
2015-03-28 08:33:16:954 MTProgramTableView>awakeFromNib@54>ProgramTable awakeFromNib
2015-03-28 08:33:16:954 MTProgramTableView>awakeFromNib@54>ProgramTable awakeFromNib
2015-03-28 08:33:16:954 MTProgramTableView>awakeFromNib@54>ProgramTable awakeFromNib
2015-03-28 08:33:16:955 MTProgramTableView>awakeFromNib@54>ProgramTable awakeFromNib
2015-03-28 08:33:16:955 MTProgramTableView>awakeFromNib@54>ProgramTable awakeFromNib
2015-03-28 08:33:16:971 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:973 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:973 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:973 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:974 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:976 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:977 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:978 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:978 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:978 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:979 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:980 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:981 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:981 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:982 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:983 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:984 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:984 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:984 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:985 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
2015-03-28 08:33:16:985 MTDownloadTableView>awakeFromNib@109>DL Table awakeFromNib
-----------------------------------------------------------------------------------------------------

**Comment by kcossabo** [comment]
As soon as I cleared history of downloaded shows, the queue started to process.

**Comment by mackworth** [comment]
Sorry, didn't get a notification on this one.  Is this beta7? I fixed one just like this in an earlier release.

So I'm seeing the Romio TiVo get notified of a new download and then not launch it ("Romio-living room (192.168.11.162:80/443) Checking for new download"), which is strange. It will definitely do this during startup (where some of the previously queued downloads are not yet matched with a show on the Tivo), but that doesn't sound like the case here. The other reason it will do this if there are encodes already under way or if the Tivo isn't reachable. Again, doesn't sound like the reason. 

So, if you are running beta 7, let me know, and I'll generate a test version that gives more info on why it's blocking here.

**Comment by kcossabo** [comment]
Thank you for the great product, and the help

Version 2.4.0b4 (509)

When I ‘cleared’ the previous downloads, the program started to download again. Also I noticed tonight (this app runs on a iMac that I do not look at daily) that ‘TiVo: Romio-Livingroom off line’

When I tried to download one of the previous shows that did not, it did not start the download. I upped the logging, closed the app, and relaunced and the queue started???

Anyways, if it helps attached I can send logs. I tried to email but it bounced.

**Comment by kcossabo** [comment]
Still occurring. If I clear the download history it unsticks.


4/14/15 11:20:51.122 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:20:51.977 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:20:51.977 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:20:52.915 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:20:52.915 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:20:53.711 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:20:53.712 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:21:20.751 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:21:20.751 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:21:23.918 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:21:23.919 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:22:02.182 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:22:02.182 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:22:02.817 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:22:02.817 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:22:03.109 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:22:03.109 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:22:05.048 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:22:05.048 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:23:33.399 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:23:33.399 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:23:33.861 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:23:33.862 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:23:34.207 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:23:34.207 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:23:36.031 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:23:36.031 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:26:35.949 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:26:35.949 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:28:11.164 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:28:11.164 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:28:12.034 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:28:12.034 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:28:26.044 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:28:26.045 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:29:23.286 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:29:23.286 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:29:24.008 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:29:24.009 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:29:24.922 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:29:24.922 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:29:25.779 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:29:25.779 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:30:23.198 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:30:23.199 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:30:23.389 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:30:23.389 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:30:25.217 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:30:25.217 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:30:27.539 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:30:27.539 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:31:00.234 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:31:00.234 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:31:00.963 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:31:00.963 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:31:01.854 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:31:01.854 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:31:02.651 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:31:02.651 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:33:23.442 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:33:23.443 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:33:24.250 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:33:24.250 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:33:25.188 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:33:25.189 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:33:26.175 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:33:26.176 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:34:00.370 AM nbagent[2064]: XPC Activity invoked with state=2
4/14/15 11:34:07.994 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:34:07.994 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:34:10.784 AM secd[223]:  securityd_xpc_dictionary_handler cTiVo[22009] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)
4/14/15 11:34:10.784 AM cTiVo[22009]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))
4/14/15 11:34:10.935 AM xpcproxy[24750]: assertion failed: 13F34: xpcproxy + 3438 [D559FC96-E6B1-363A-B850-C7AC9734F210]: 0x2
4/14/15 11:38:14.232 AM WindowServer[106]: CGXDisplayDidWakeNotification [1483007376960782]: posting kCGSDisplayDidWake
4/14/15 11:38:14.233 AM WindowServer[106]: handle_will_sleep_auth_and_shield_windows: Deferring.
4/14/15 11:38:30.173 AM mDNSResponder[73]:  47: Could not write data to clientPID[24765](com.apple.WebKi)  because of error - aborting connection
4/14/15 11:38:30.173 AM mDNSResponder[73]:  47: DNSServiceGetAddrInfo      v4v6 collector.githubapp.com. PID[24765](com.apple.WebKi)

**Comment by mackworth** [comment]
Did this get resolved with beta7?

**Comment by kcossabo** [comment]
I will need to check. I was using the updat check built into the app and it did not say there was an update.

**Comment by mackworth** [comment]
As I'm still chasing a crash, I haven't triggered the update mechanism yet.

**Comment by kcossabo** [comment]
did not fix the issue, b7 caused new ones :(

5/16/15 7:03:20.000 AM kernel[0]: process cTiVo[161] thread 1298 caught burning CPU! It used more than 50% CPU (Actual recent usage: 70%) over 180 seconds. thread lifetime cpu usage 90.326026 seconds, (88.863607 user, 1.462419 system) ledger info: balance: 90007111480 credit: 90007111480 debit: 0 limit: 90000000000 (50%) period: 180000000000 time since last refill (ns): 126924547623 

5/16/15 7:03:20.330 AM ReportCrash[315]: Invoking spindump for pid=161 thread=1298 percent_cpu=70 duration=129 because of excessive cpu utilization

5/16/15 7:03:21.438 AM spindump[316]: Saved cpu_resource.spin report for cTiVo version 2.4.0b7 (534) to /Library/Logs/DiagnosticReports/cTiVo_2015-05-16-070321_cTiVo-iMac-4.cpu_resource.spin



Kevin Cossaboon
kevin.cossaboon@me.com

**Comment by kcossabo** [comment]
the spin dump is large, and can not attach. let me know if you wish it.

**Comment by mackworth** [comment]
I've found a crashing bug that might be related. Can you try version 8 and see how it does for you?

**Comment by kcossabo** [comment]
will try now. Thank you 

Kevin Cossaboon
kevin.cossaboon@me.com

**Comment by kcossabo** [comment]
Hugh, no joy….

cTiVo b8

5/19/15 7:37:44.000 AM kernel[0]: process cTiVo[6799] thread 2221332 caught burning CPU! It used more than 50% CPU (Actual recent usage: 87%) over 180 seconds. thread lifetime cpu usage 90.243760 seconds, (88.152082 user, 2.091678 system) ledger info: balance: 90002445012 credit: 90002445012 debit: 0 limit: 90000000000 (50%) period: 180000000000 time since last refill (ns): 102962237341 

5/19/15 7:37:44.653 AM ReportCrash[6807]: Invoking spindump for pid=6799 thread=2221332 percent_cpu=87 duration=104 because of excessive cpu utilization

5/19/15 7:37:46.056 AM spindump[6808]: Saved cpu_resource.spin report for cTiVo version 2.4.0b8 (537) to /Library/Logs/DiagnosticReports/cTiVo_2015-05-19-073746_cTiVo-iMac-4.cpu_resource.spin

5/19/15 7:38:06.239 AM cTiVo[6799]: BUG in libdispatch client: kevent[EVFILT_VNODE] delete: "Bad file descriptor" - 0x9

5/19/15 7:38:21.437 AM com.apple.SecurityServer[15]: Session 100054 created


———————
Second launch 20 min later, as cTiVo did not Finnish update
—————————

5/19/15 8:00:25.447 AM cTiVo[6841]: Invalid color System, labelColor (warning given only once)

5/19/15 8:00:39.264 AM secd[238]:  securityd_xpc_dictionary_handler cTiVo[6841] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)

5/19/15 8:00:39.265 AM cTiVo[6841]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))

5/19/15 8:00:48.074 AM cTiVo[6841]: BUG in libdispatch client: kevent[EVFILT_VNODE] delete: "Bad file descriptor" - 0x9

5/19/15 8:02:37.000 AM kernel[0]: process cTiVo[6841] thread 2227927 caught burning CPU! It used more than 50% CPU (Actual recent usage: 68%) over 180 seconds. thread lifetime cpu usage 90.206526 seconds, (89.287701 user, 0.918825 system) ledger info: balance: 90008197961 credit: 90008197961 debit: 0 limit: 90000000000 (50%) period: 180000000000 time since last refill (ns): 131906416842 

5/19/15 8:02:37.184 AM ReportCrash[6849]: Invoking spindump for pid=6841 thread=2227927 percent_cpu=68 duration=133 because of excessive cpu utilization

5/19/15 8:02:37.904 AM spindump[6850]: Saved cpu_resource.spin report for cTiVo version 2.4.0b8 (537) to /Library/Logs/DiagnosticReports/cTiVo_2015-05-19-080237_cTiVo-iMac-4.cpu_resource.spin

—————————

if it matters;

iMac
27-inch, Mid 2011
Processor  3.4 GHz Intel Core i7

Memory  16 GB 1333 MHz DDR3

Software  OS X 10.9.5 (13F34)






Kevin Cossaboon
kevin.cossaboon@me.com

**Comment by mackworth** [comment]
the filenode error is strange. Could you run Disk Utility>Verify Disk and Repair Permissions on your hard drive? Assuming that doesn't fix it, then I'll have to spend more time on this one, as I don't think this is the same problem I've seen in Yosemite. If you could post the cTiVo logs somewhere and post a URL here, that would be great.

The labelColor one is my fault (a new thing in Yosemite that I apparently am calling in previous OS.)

**Comment by kcossabo** [comment]
will do…


Kevin Cossaboon
kevin.cossaboon@me.com

**Comment by kcossabo** [comment]
Sir

Logs are at 

https://www.dropbox.com/sh/a27990leeemiijo/AAAKGenO-VLxiWgiBeg4rP3Qa?dl=0 <https://www.dropbox.com/sh/a27990leeemiijo/AAAKGenO-VLxiWgiBeg4rP3Qa?dl=0>

I keep going back to V2.3..1.(468) as it seems to work ok. Just mention that for your reference

Once again, Thank you for developing a GREAT program!!


Kevin Cossaboon
kevin.cossaboon@me.com

**Comment by mackworth** [comment]
Thanks. Do you have the cTivo logs ( ~/Library/Logs/cTiVo ) as well?

**Comment by kcossabo** [comment]
Hugh

Should be on the same share under a new directory.


Kevin Cossaboon
kevin.cossaboon@me.com

**Comment by mackworth** [comment]
So your Tivo is reporting that it has 613 items, but as we ask for them, it stops returning items at 610. Unfortunately, my code apparently thinks this is rude, so it just asks again, and again, and so on.  See truncated version below.

So, one thought is you should reboot your TiVo, but before you do that, here's a trial version that should take a hint and stop asking:

https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

Let me know if that helps; it should continue on, but put an error message in the log "TiVo returned ZERO items". regardless, look at your oldest entries on your TiVo (including suggestions) to see if they are copied over properly to cTiVo or not.

Still I would also do a Disk Utility volume and permissions check on that drive.

````
2015-05-19 09:48:45:111 MTTiVo>connectionDidFinishLoading:@804>
Data received is ...<Title>Now Playing</Title>... 
<TotalItems>613</TotalItems>
<ItemStart>610</ItemStart>
<ItemCount>0</ItemCount>
</TiVoContainer>
````

**Comment by mackworth** [comment]
Oh, and you shouldn't be getting the labelColor error, nor the Keychain warnings

**Comment by kcossabo** [comment]
With Respect To the reboot of the TiVo, been there done that. I think the issue is the change from Season Pass to One Pass they dropped CNET video casts and there is a mix up in the TiVo Directory (guess). I will try the new code.


Kevin Cossaboon
kevin.cossaboon@me.com

**Comment by kcossabo** [comment]
Sir

QUICK CRASH on that version. did not even get to the gui

The crash and log are on the dropbox link under ‘test version log'

Kevin Cossaboon
kevin.cossaboon@me.com

**Comment by mackworth** [comment]
Sorry 'bout that; a codesigning issue.  Please try again:   https://dl.dropboxusercontent.com/u/21507587/cTiVo.zip

**Comment by kcossabo** [comment]
Hugh

So far so good….

I see only two set of these two on the console, I put the new log on the dropbox site. I launched and did not keep trying to update, and I clicked on a show that I do not subscribe to and added it to the Queue. Downloading started.


——————

5/21/15 6:51:55.607 AM secd[246]:  securityd_xpc_dictionary_handler cTiVo[3374] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)

5/21/15 6:51:55.609 AM cTiVo[3374]:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))

5/21/15 6:52:34.564 AM secd[246]:  securityd_xpc_dictionary_handler cTiVo[3374] copy_matching The operation couldn’t be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements)



——————


Kevin Cossaboon
kevin.cossaboon@me.com

**Comment by mackworth** [comment]
That's excellent. The 34018 error was expected, as my fix was related to the codesigning. Not sure it can be fixed without being in the Mac App Store.

I'll close this out, but let me know if any thing happens.
